name: Docker CI/CD
 
on:
  push:
    branches:
      - main
 
env:
  IMAGE_REPO_NAME: dainmusty/effulgencetech-nodejs-img
  CONTAINER_NAME: effulgencetech-nodejs-cont
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
 
      - name: Clean up Docker system
        run: |
          docker system prune -f
          docker container prune -f
 
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_REPO_NAME:${{ github.run_number }} .
 
      - name: Show Docker images
        run: docker images
 
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_REPO_NAME:${{ github.run_number }}
 
      - name: Run Docker container
        run: |
          docker run --name $CONTAINER_NAME-${{ github.run_number }} -p 8084:8080 -d $IMAGE_REPO_NAME:${{ github.run_number }}
          docker ps